/**
 *
 * $Id$
 */
package SistemaEncuestas.validation;

import SistemaEncuestas.Fin;
import SistemaEncuestas.Respuesta;

/**
 * A sample validator interface for {@link SistemaEncuestas.SaltoFinRespuesta}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SaltoFinRespuestaValidator {
	boolean validate();

	boolean validateDestino(Fin value);
	boolean validateOrigen(Respuesta value);
}
